INSERT INTO Country (CountryName, NationalityName) VALUES
('Poland', 'Polish'),
('Germany', 'German'),
('France', 'French'),
('Italy', 'Italian'),
('Spain', 'Spanish'),
('Portugal', 'Portuguese'),
('Netherlands', 'Dutch'),
('Belgium', 'Belgian'),
('Austria', 'Austrian'),
('Sweden', 'Swedish'),
('Denmark', 'Danish'),
('Finland', 'Finnish'),
('Ireland', 'Irish'),
('Czech Republic', 'Czech'),
('Slovakia', 'Slovak'),
('Hungary', 'Hungarian'),
('Croatia', 'Croatian'),
('Slovenia', 'Slovenian'),
('Bulgaria', 'Bulgarian'),
('Romania', 'Romanian'),
('Greece', 'Greek'),
('Cyprus', 'Cypriot'),
('Estonia', 'Estonian'),
('Latvia', 'Latvian'),
('Lithuania', 'Lithuanian'),
('Luxembourg', 'Luxembourgish'),
('Malta', 'Maltese');